### ISSUE TITLE
Hi what the difference between babel-plugin-syntax-pipeline ?

### ISSUE THREAD

**Issue by OlegLustenko** [SuperPaintman/babel-plugin-transform-pipeline#3]
Hi as I see you maintaine two repos:
1) [babel-plugin-syntax-pipeline](https://github.com/SuperPaintman/babel-plugin-syntax-pipeline)
2) [babel-plugin-transform-pipeline](https://github.com/SuperPaintman/babel-plugin-transform-pipeline)

They seem same, what the difference, which one to use?

**Comment by SuperPaintman** [comment]
**syntax** just adds a `|>` token support in a tokenize state. And it is a dependency for **transform**:

https://github.com/SuperPaintman/babel-plugin-transform-pipeline/blob/master/package.json#L35

**Comment by OlegLustenko** [comment]
Ok, I see thanks, readme for [babel-plugin-transform-pipeline]() confused me

**Comment by SuperPaintman** [comment]
Why? What's wrong with the `README`?
